---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: Sie können E-Mails einrichten, um Berichte des Upgrade Health Checkers zu erhalten. 
---
= Erhalten Sie Upgrade Health Checker-Berichte per E-Mail
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker kann Berichte direkt an Ihren Posteingang senden. Diese Funktion kann über die Datei config.yaml oder ein Befehlszeilenargument aktiviert werden. Wenn aktiviert, sendet Upgrade Health Checker generierte Berichte (HTML, Excel oder JSON) über einen SMTP-Server an einen oder mehrere Empfänger. Wenn deaktiviert, werden keine Berichte gesendet. Wenn die Berichtserstellung fehlschlägt und der E-Mail-Versand aktiviert ist, sendet Upgrade Health Checker die Protokolldateien an die konfigurierten Empfänger.



[[configure-using-the-config-yaml-file]]
== Konfigurieren Sie die Datei config.yaml.

Sie können die E-Mail-Einstellungen in der Datei config.yaml konfigurieren, indem Sie E-Mail-Berichte aktivieren, SMTP-Serverdetails hinzufügen und Empfängeradressen sowie Berichtsformate angeben.

. Aktivieren Sie E-Mail-Berichte in der config.yaml-Datei.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Die SMTP-Konfigurationseinstellungen, die Absenderdetails und den Betreff hinzufügen:
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Fügen Sie die E-Mail-Adressen der Empfänger hinzu und legen Sie fest, welche Berichtsformate das System per E-Mail versendet, zum Beispiel HTML, EXCEL, JSON oder ALL. Auch Authentifizierung und Verschlüsselung sind möglich:
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== Konfiguration mit Befehlszeilenargumenten

Grundlegende E-Mail-Einstellungen lassen sich mithilfe von Befehlszeilenargumenten konfigurieren, um Berichte zu aktivieren, Empfänger anzugeben und Berichtsformate auszuwählen.

. E-Mail-Berichte mithilfe von Befehlszeilenargumenten aktivieren:
+
[listing]
----
./uhc --email-enabled=true
----
. E-Mail-Adressen der Empfänger angeben:
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Konfigurieren Sie, welche Berichtsformate per E-Mail versendet werden, z. B. HTML, EXCEL, JSON:
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
Die folgenden drei Attribute lassen sich über Befehlszeilenargumente oder die Datei config.yaml konfigurieren. Alle übrigen Attribute sind ausschließlich in der Datei config.yaml konfigurierbar:

* E-Mail-fähig
* E-Mail-Empfänger
* E-Mail-Berichtsformate


Zu beachten ist, dass Befehlszeilenargumente die Werte der Datei config.yaml überschreiben.

Beispiel:

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====